use 64bit filesystem offsets/sizes everywhere
mendersoftware/mender-flash pull request #18
Opened 2024-11-04 15:00 UTC by JohannesSchilling

this improves compatibility with musl, which only exposes the 64bit variants, but without the "64" name suffix.

2024-11-05 06:00 UTC, kacf requested changes
Thanks @JohannesSchilling!

A couple of housekeeping nitpicks:

* Could you add a Signoff line to your commit (use `git commit -s`)? It's a legal requirement for contributions.
* Can you also add a `Changelog: Title` tag to the commit message?

Otherwise the change looks good!

2024-11-05 10:03 UTC, JohannesSchilling commented
hm, any ticket i can link here @kacf? should i just put something like `MEN-0000` or `MEN-None`?

2024-11-05 10:06 UTC, kacf commented
I don't think there is a ticket for this, you can just put `None`.

2024-11-06 08:08 UTC, kacf approved these changes
Thanks!

2024-11-06 08:15 UTC, merged